[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_marketplace = "ptcbSp1UEqYLmod2jgFxGPZnFMqBECcrRyU1fTmnJ5b"

[programs.devnet]
nft_marketplace = "ptcbSp1UEqYLmod2jgFxGPZnFMqBECcrRyU1fTmnJ5b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ekutlugun/Projects/VYBE/marketplacemetaplex/.keys/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.31.1"
